markdown: kramdown
highlighter: pygments
permalink: /news/:year/:month/:day/:title/
#url: http://ic.apexnet.it
baseurl:
excerpt_separator: ""

#gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-20354938-22

repository: https://github.com/Apex-net/icommerce-site
help_url: https://github.com/Apex-net/icommerce-site

collections:
  docs:
    output: true
